/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wanglei_kociemba_Kociemba */

#ifndef _Included_com_wanglei_kociemba_Kociemba
#define _Included_com_wanglei_kociemba_Kociemba
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wanglei_kociemba_Kociemba
 * Method:    solution
 * Signature: (Ljava/lang/String;IJILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wanglei_kociemba_Kociemba_solution
  (JNIEnv *, jclass, jstring, jint, jlong, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
